fix(builtins/diagnostics/clazy): Handle fatal errors
clazy can sometimes output fatal errors, for example when a file doesn't
exist:

main.cpp:1:10: fatal error: 'non-existent' file not found
 #include <non-existent>
         ^~~~~~~~~~~~~~
1 error generated.

These weren't caught by the regex and that resulted in 'msg' being nil.

Fix this by allowing a space when parsing the severity.